name: taller_rodriguez
description: "Frontend para el taller de rodriguez"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  equatable: ^2.0.5
  http: ^1.6.0
  fl_chart: ^1.2.0
  flutter_dotenv: ^6.0.1
  pdf: ^3.11.0
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo_taller.png
    - assets/sidebar_false/
    - assets/sidebar_true/
    - assets/fonts/
  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
          weight: 700